# This is a basic workflow to help you get started with Actions

name: Build and upload .exe file

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the "main" branch
  push:
    branches: [ "main" ]

  schedule:
    - cron: "0 12 * * 1"

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: macos-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v4

      - name: Set up python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'

      - name: Install packages
        run: |
          sh installResources.sh

      - name: Build .exe with PyInstaller
        run: |
          pyinstaller --onefile --noconsole cprogram.py
          
      - name: Upload EXE artifact
        uses: actions/upload-artifact@v3
        with:
          name: cprogram-exe
          path: dist/cprogram.exe
